// AUTO-GENERATED by scripts/siddur/10_assemble.mjs — do not edit
import type { SiddurSection } from '../../../siddur/types';
export const SECTIONS = {
  aleinu_maariv: () => require('./aleinu_maariv.json') as SiddurSection,
  birchos_krias_shema_maariv: () => require('./birchos_krias_shema_maariv.json') as SiddurSection,
  ldovid_hashem_maariv: () => require('./ldovid_hashem_maariv.json') as SiddurSection,
  maariv_motzaei_shabbos: () => require('./maariv_motzaei_shabbos.json') as SiddurSection,
  maariv_opening: () => require('./maariv_opening.json') as SiddurSection,
  shemoneh_esrei_maariv: () => require('./shemoneh_esrei_maariv.json') as SiddurSection,
} as const;
export type SectionKey = keyof typeof SECTIONS;
