// AUTO-GENERATED by scripts/siddur/10_assemble.mjs — do not edit
import type { SiddurSection } from '../../../siddur/types';
export const SECTIONS = {
  birchas_hamazon: () => require('./birchas_hamazon.json') as SiddurSection,
  al_hamichyah: () => require('./al_hamichyah.json') as SiddurSection,
  borei_nefashos: () => require('./borei_nefashos.json') as SiddurSection,
} as const;
export type SectionKey = keyof typeof SECTIONS;
