// AUTO-GENERATED by scripts/siddur/10_assemble.mjs — do not edit
import type { SiddurSection } from '../../../siddur/types';
export const SECTIONS = {
  aleinu_mincha: () => require('./aleinu_mincha.json') as SiddurSection,
  avinu_malkeinu_mincha: () => require('./avinu_malkeinu_mincha.json') as SiddurSection,
  mincha_ashrei: () => require('./mincha_ashrei.json') as SiddurSection,
  shemoneh_esrei_mincha: () => require('./shemoneh_esrei_mincha.json') as SiddurSection,
  tachanun_mincha: () => require('./tachanun_mincha.json') as SiddurSection,
} as const;
export type SectionKey = keyof typeof SECTIONS;
