// AUTO-GENERATED by scripts/siddur/10_assemble.mjs — do not edit
import type { SiddurSection } from '../../../siddur/types';
export const SECTIONS = {
  aleinu_shacharit: () => require('./aleinu_shacharit.json') as SiddurSection,
  avinu_malkeinu_shacharit: () => require('./avinu_malkeinu_shacharit.json') as SiddurSection,
  barchi_nafshi: () => require('./barchi_nafshi.json') as SiddurSection,
  barchu: () => require('./barchu.json') as SiddurSection,
  birchos_hashachar: () => require('./birchos_hashachar.json') as SiddurSection,
  birchos_krias_shema_shacharit: () => require('./birchos_krias_shema_shacharit.json') as SiddurSection,
  hallel: () => require('./hallel.json') as SiddurSection,
  hashkamas_haboker: () => require('./hashkamas_haboker.json') as SiddurSection,
  krias_hatorah: () => require('./krias_hatorah.json') as SiddurSection,
  ldovid_hashem_shacharit: () => require('./ldovid_hashem_shacharit.json') as SiddurSection,
  mussaf_chol_hamoed: () => require('./mussaf_chol_hamoed.json') as SiddurSection,
  mussaf_rosh_chodesh: () => require('./mussaf_rosh_chodesh.json') as SiddurSection,
  pesukei_dzimrah: () => require('./pesukei_dzimrah.json') as SiddurSection,
  pitum_haketores: () => require('./pitum_haketores.json') as SiddurSection,
  shemoneh_esrei_shacharit: () => require('./shemoneh_esrei_shacharit.json') as SiddurSection,
  shesh_zechiros: () => require('./shesh_zechiros.json') as SiddurSection,
  shir_shel_yom: () => require('./shir_shel_yom.json') as SiddurSection,
  shloshah_asar_ikarim: () => require('./shloshah_asar_ikarim.json') as SiddurSection,
  tachanun_shacharit: () => require('./tachanun_shacharit.json') as SiddurSection,
} as const;
export type SectionKey = keyof typeof SECTIONS;
