// AUTO-GENERATED by scripts/siddur/10_assemble.mjs — do not edit
import type { CardId, SiddurSection } from '../../siddur/types';
import { SECTIONS as SHACHARIT } from './shacharit';
import { SECTIONS as BIRKAT_HAMAZON } from './birkat_hamazon';
import { SECTIONS as MINCHA } from './mincha';
import { SECTIONS as MAARIV } from './maariv';
import { SECTIONS as TEFILLOS } from './tefillos';

const REGISTRY: Record<string, Record<string, () => SiddurSection>> = {
  shacharit: SHACHARIT,
  birkat_hamazon: BIRKAT_HAMAZON,
  mincha: MINCHA,
  maariv: MAARIV,
  tefillos: TEFILLOS,
  learn: {},
};

export function getSiddurSection(cardId: CardId, sectionId: string): SiddurSection | null {
  const loader = REGISTRY[cardId]?.[sectionId];
  if (!loader) return null;
  return loader();
}

export function listSectionIds(cardId: CardId): string[] {
  return Object.keys(REGISTRY[cardId] ?? {});
}
