// AUTO-GENERATED by scripts/siddur/10_assemble.mjs — do not edit
import type { SiddurSection } from '../../../siddur/types';
export const SECTIONS = {
  tefillas_haderech: () => require('./tefillas_haderech.json') as SiddurSection,
  sefiras_haomer: () => require('./sefiras_haomer.json') as SiddurSection,
  krias_shema_al_hamitah: () => require('./krias_shema_al_hamitah.json') as SiddurSection,
  netilas_lulav: () => require('./netilas_lulav.json') as SiddurSection,
} as const;
export type SectionKey = keyof typeof SECTIONS;
