// AUTO-GENERATED by scripts/siddur/10_assemble.mjs — do not edit
import type { LearnEssay } from '../../../siddur/types';
export const ESSAYS = {
  acknowledgments: () => require('./acknowledgments.json') as LearnEssay,
  appendix_01_how_davening_works: () => require('./appendix_01_how_davening_works.json') as LearnEssay,
  appendix_02_tzaddik_vra_lo: () => require('./appendix_02_tzaddik_vra_lo.json') as LearnEssay,
  appendix_03_positive_power_of_mistakes: () => require('./appendix_03_positive_power_of_mistakes.json') as LearnEssay,
  appendix_04_am_segulah: () => require('./appendix_04_am_segulah.json') as LearnEssay,
  appendix_05_bechirah_chofshis: () => require('./appendix_05_bechirah_chofshis.json') as LearnEssay,
  appendix_06_siyata_dshmaya: () => require('./appendix_06_siyata_dshmaya.json') as LearnEssay,
  appendix_07_all_hashem_does_is_good: () => require('./appendix_07_all_hashem_does_is_good.json') as LearnEssay,
  appendix_08_our_material_world: () => require('./appendix_08_our_material_world.json') as LearnEssay,
  appendix_09_korbanos: () => require('./appendix_09_korbanos.json') as LearnEssay,
  appendix_10_making_hashem_happy: () => require('./appendix_10_making_hashem_happy.json') as LearnEssay,
  appendix_11_ben_torah_bas_yisrael: () => require('./appendix_11_ben_torah_bas_yisrael.json') as LearnEssay,
  appendix_12_halachos: () => require('./appendix_12_halachos.json') as LearnEssay,
  glossary: () => require('./glossary.json') as LearnEssay,
  introduction_for_parents: () => require('./introduction_for_parents.json') as LearnEssay,
  introduction_for_teens: () => require('./introduction_for_teens.json') as LearnEssay,
  personal_note_to_parents: () => require('./personal_note_to_parents.json') as LearnEssay,
  personal_note_to_teens: () => require('./personal_note_to_teens.json') as LearnEssay,
} as const;
export type EssayKey = keyof typeof ESSAYS;
