'use strict';

/**
 * Stage 10 tests — Final JSON assembly into src/data/siddur/.
 *
 * CJS test file (jest-expo preset does not support .mjs transforms for scripts).
 * Integration tests assert on written output files generated by 10_assemble.mjs.
 */

const { execFileSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const SIDDUR_DIR = path.join(REPO_ROOT, 'src', 'data', 'siddur');
const LEARN_DIR = path.join(SIDDUR_DIR, 'learn');
const STAGE10_SCRIPT = path.join(REPO_ROOT, 'scripts', 'siddur', '10_assemble.mjs');

// Run stage 10 if key outputs are missing
const BOREI_NEFASHOS_PATH = path.join(SIDDUR_DIR, 'birkat_hamazon', 'borei_nefashos.json');
const SHACHARIT_INDEX_PATH = path.join(SIDDUR_DIR, 'shacharit', 'index.ts');
if (!fs.existsSync(BOREI_NEFASHOS_PATH) || !fs.existsSync(SHACHARIT_INDEX_PATH)) {
  console.log('Stage 10 outputs missing — running stage script…');
  execFileSync(process.execPath, [STAGE10_SCRIPT], { stdio: 'inherit' });
}

// ─── Test 1: borei_nefashos.json exists with required SiddurSection fields ───

describe('Stage 10 — borei_nefashos.json is a valid SiddurSection', () => {
  let data;

  beforeAll(() => {
    data = JSON.parse(fs.readFileSync(BOREI_NEFASHOS_PATH, 'utf8'));
  });

  test('file exists', () => {
    expect(fs.existsSync(BOREI_NEFASHOS_PATH)).toBe(true);
  });

  test('has source === feigenbaum', () => {
    expect(data.source).toBe('feigenbaum');
  });

  test('has id field', () => {
    expect(data.id).toBe('borei_nefashos');
  });

  test('has cardId field', () => {
    expect(data.cardId).toBe('birkat_hamazon');
  });

  test('has blocks array', () => {
    expect(Array.isArray(data.blocks)).toBe(true);
    expect(data.blocks.length).toBeGreaterThan(0);
  });

  test('has sourcePages tuple [start, end]', () => {
    expect(Array.isArray(data.sourcePages)).toBe(true);
    expect(data.sourcePages).toHaveLength(2);
  });

  test('has title with en field', () => {
    expect(data.title).toBeDefined();
    expect(typeof data.title.en).toBe('string');
    expect(data.title.en.length).toBeGreaterThan(0);
  });
});

// ─── Test 2: shacharit/index.ts exists and contains hashkamas_haboker ────────

describe('Stage 10 — shacharit/index.ts is correct', () => {
  let content;

  beforeAll(() => {
    content = fs.readFileSync(SHACHARIT_INDEX_PATH, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SHACHARIT_INDEX_PATH)).toBe(true);
  });

  test('contains hashkamas_haboker', () => {
    expect(content).toContain('hashkamas_haboker');
  });

  test('contains require() thunk pattern', () => {
    expect(content).toContain('require(');
  });

  test('imports SiddurSection type', () => {
    expect(content).toContain('SiddurSection');
  });

  test('exports SECTIONS const', () => {
    expect(content).toContain('export const SECTIONS');
  });
});

// ─── Test 3: appendix_09_korbanos.json has essayKind === appendix ────────────

describe('Stage 10 — appendix_09_korbanos.json is a valid LearnEssay', () => {
  let data;
  const ESSAY_PATH = path.join(LEARN_DIR, 'appendix_09_korbanos.json');

  beforeAll(() => {
    data = JSON.parse(fs.readFileSync(ESSAY_PATH, 'utf8'));
  });

  test('file exists', () => {
    expect(fs.existsSync(ESSAY_PATH)).toBe(true);
  });

  test('has essayKind === appendix', () => {
    expect(data.essayKind).toBe('appendix');
  });

  test('has source === feigenbaum', () => {
    expect(data.source).toBe('feigenbaum');
  });

  test('anchoredFrom has no position field', () => {
    for (const entry of data.anchoredFrom || []) {
      expect(entry).not.toHaveProperty('position');
      expect(entry).toHaveProperty('cardId');
      expect(entry).toHaveProperty('sectionId');
    }
  });
});

// ─── Test 4: main index.ts imports from per-card indexes ─────────────────────

describe('Stage 10 — src/data/siddur/index.ts dispatches to per-card indexes', () => {
  let content;
  const INDEX_PATH = path.join(SIDDUR_DIR, 'index.ts');

  beforeAll(() => {
    content = fs.readFileSync(INDEX_PATH, 'utf8');
  });

  test('imports from ./shacharit', () => {
    expect(content).toContain("from './shacharit'");
  });

  test('exports getSiddurSection function', () => {
    expect(content).toContain('export function getSiddurSection');
  });

  test('exports listSectionIds function', () => {
    expect(content).toContain('export function listSectionIds');
  });

  test('does not reference seed fixture', () => {
    expect(content).not.toContain('seed.json');
    expect(content).not.toContain("'seed'");
  });
});

// ─── Test 5: type-conformance checks on assembled sections ───────────────────

describe('Stage 10 — type conformance of assembled blocks', () => {
  test('learn_link blocks use promptText, not label', () => {
    const pitumPath = path.join(SIDDUR_DIR, 'shacharit', 'pitum_haketores.json');
    const data = JSON.parse(fs.readFileSync(pitumPath, 'utf8'));
    const links = data.blocks.filter((b) => b.kind === 'learn_link');
    expect(links.length).toBeGreaterThan(0);
    for (const link of links) {
      expect(link).not.toHaveProperty('label');
      expect(link).toHaveProperty('promptText');
    }
  });

  test('rubric blocks have italic:true', () => {
    const hallelPath = path.join(SIDDUR_DIR, 'shacharit', 'hallel.json');
    const data = JSON.parse(fs.readFileSync(hallelPath, 'utf8'));
    const rubrics = data.blocks.filter((b) => b.kind === 'rubric');
    expect(rubrics.length).toBeGreaterThan(0);
    for (const r of rubrics) {
      expect(r.italic).toBe(true);
      expect(r.text).toBeDefined();
      expect(typeof r.text.en).toBe('string');
    }
  });

  test('date_window conditionalRule uses from/to with kind:month_day', () => {
    const ldovidPath = path.join(SIDDUR_DIR, 'shacharit', 'ldovid_hashem_shacharit.json');
    const data = JSON.parse(fs.readFileSync(ldovidPath, 'utf8'));
    const cr = data.conditionalRule;
    expect(cr).toBeDefined();
    expect(cr.type).toBe('date_window');
    expect(cr.from).toBeDefined();
    expect(cr.from.kind).toBe('month_day');
    expect(typeof cr.from.month).toBe('string');
    expect(typeof cr.from.day).toBe('number');
    expect(cr.to).toBeDefined();
    expect(cr.to.kind).toBe('month_day');
    expect(cr).not.toHaveProperty('start');
    expect(cr).not.toHaveProperty('end');
  });

  test('hallel conditionalRule has variant field', () => {
    const hallelPath = path.join(SIDDUR_DIR, 'shacharit', 'hallel.json');
    const data = JSON.parse(fs.readFileSync(hallelPath, 'utf8'));
    const cr = data.conditionalRule;
    expect(cr).toBeDefined();
    expect(cr.type).toBe('hallel');
    expect(cr.variant).toBeDefined();
    expect(['full', 'half']).toContain(cr.variant);
  });

  test('prayer blocks have no translit in main JSON (moved to sidecar)', () => {
    const hashkamasPath = path.join(SIDDUR_DIR, 'shacharit', 'hashkamas_haboker.json');
    const data = JSON.parse(fs.readFileSync(hashkamasPath, 'utf8'));
    const prayers = data.blocks.filter((b) => b.kind === 'prayer');
    for (const p of prayers) {
      expect(p).not.toHaveProperty('translit');
    }
  });

  test('translit sidecar exists for hashkamas_haboker', () => {
    const sidecarPath = path.join(SIDDUR_DIR, 'shacharit', 'hashkamas_haboker.translit.json');
    expect(fs.existsSync(sidecarPath)).toBe(true);
    const sidecar = JSON.parse(fs.readFileSync(sidecarPath, 'utf8'));
    expect(Array.isArray(sidecar)).toBe(true);
    expect(sidecar.length).toBeGreaterThan(0);
    for (const entry of sidecar) {
      expect(typeof entry.blockIndex).toBe('number');
      expect(Array.isArray(entry.translit)).toBe(true);
    }
  });

  test('callout blocks have no rawText field', () => {
    const hashkamasPath = path.join(SIDDUR_DIR, 'shacharit', 'hashkamas_haboker.json');
    const data = JSON.parse(fs.readFileSync(hashkamasPath, 'utf8'));
    const callouts = data.blocks.filter((b) => b.kind === 'callout' || b.kind === 'instant_insight');
    for (const c of callouts) {
      expect(c).not.toHaveProperty('rawText');
      expect(Array.isArray(c.body)).toBe(true);
    }
  });

  test('block-level conditionalTags hoisted to section-level for krias_hatorah', () => {
    const kriaspath = path.join(SIDDUR_DIR, 'shacharit', 'krias_hatorah.json');
    const data = JSON.parse(fs.readFileSync(kriaspath, 'utf8'));
    // Section-level conditionalTags should exist
    expect(Array.isArray(data.conditionalTags)).toBe(true);
    expect(data.conditionalTags.length).toBeGreaterThan(0);
    // Each entry has blockIndex and rule
    for (const ct of data.conditionalTags) {
      expect(typeof ct.blockIndex).toBe('number');
      expect(ct.blockIndex).toBeGreaterThanOrEqual(0);
      expect(ct.blockIndex).toBeLessThan(data.blocks.length);
      expect(ct.rule).toBeDefined();
      expect(typeof ct.rule.type).toBe('string');
    }
    // No block should still have inline conditionalTags
    for (const block of data.blocks) {
      expect(block).not.toHaveProperty('conditionalTags');
    }
  });
});

// ─── Test 6: learn/index.ts exists and has all essays ────────────────────────

describe('Stage 10 — learn/index.ts is complete', () => {
  let content;
  const LEARN_INDEX_PATH = path.join(LEARN_DIR, 'index.ts');

  beforeAll(() => {
    content = fs.readFileSync(LEARN_INDEX_PATH, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(LEARN_INDEX_PATH)).toBe(true);
  });

  test('exports ESSAYS const', () => {
    expect(content).toContain('export const ESSAYS');
  });

  test('imports LearnEssay type', () => {
    expect(content).toContain('LearnEssay');
  });

  test('contains appendix_09_korbanos', () => {
    expect(content).toContain('appendix_09_korbanos');
  });
});
