'use strict';

/**
 * Stage 11 tests — Verification reports.
 *
 * CJS test file (jest-expo preset does not support .mjs transforms for scripts).
 * Integration tests assert on written output files generated by 11_verify.mjs.
 */

const { execFileSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const REPO_ROOT = path.resolve(__dirname, '..', '..', '..');
const REPORTS_DIR = path.join(REPO_ROOT, 'content', 'feigenbaum-2026', 'reports');
const STAGE11_SCRIPT = path.join(REPO_ROOT, 'scripts', 'siddur', '11_verify.mjs');

const REPORT_FILES = [
  'coverage_report.md',
  'translit_gaps.md',
  'italic_audit.md',
  'unanchored_essays.md',
  'block_classification.md',
];

// Run stage 11 if any report is missing
const allExist = REPORT_FILES.every((f) => fs.existsSync(path.join(REPORTS_DIR, f)));
if (!allExist) {
  console.log('Stage 11 reports missing — running stage script…');
  execFileSync(process.execPath, [STAGE11_SCRIPT], { stdio: 'inherit' });
}

// ─── Test 1: All 5 report files exist ────────────────────────────────────────

describe('Stage 11 — all 5 report files exist', () => {
  for (const fileName of REPORT_FILES) {
    test(`${fileName} exists`, () => {
      expect(fs.existsSync(path.join(REPORTS_DIR, fileName))).toBe(true);
    });
  }
});

// ─── Test 2: coverage_report.md FAIL count is within acceptable bounds ───────
//
// Some sections share PDF pages with adjacent content (e.g. barchu page 50 also
// contains pesukei d'zimra korbanos material). The 75% threshold allows up to
// 25% of characters to be explained by minyan-only filtering and page bleed.
// FAILs below the MAX_ALLOWED_FAILS threshold are documented here as known
// acceptable findings — they don't mean content is missing, just that those
// particular PDF page ranges include significant extra-section material.
const MAX_ALLOWED_FAILS = 6; // current baseline: 5 FAILs from page-bleed

describe('Stage 11 — coverage_report.md', () => {
  let content;

  beforeAll(() => {
    content = fs.readFileSync(path.join(REPORTS_DIR, 'coverage_report.md'), 'utf8');
  });

  test('file is non-empty', () => {
    expect(content.length).toBeGreaterThan(0);
  });

  test('contains OK lines (at least some sections pass coverage)', () => {
    const okLines = content.split('\n').filter((line) => line.startsWith('OK'));
    expect(okLines.length).toBeGreaterThan(0);
  });

  test('FAIL count is within acceptable baseline', () => {
    const failLines = content
      .split('\n')
      .filter((line) => line.startsWith('FAIL'));
    if (failLines.length > 0) {
      console.warn(
        `${failLines.length} coverage FAIL(s) found (page-bleed or minyan filtering):\n` +
          failLines.join('\n')
      );
    }
    // Soft check: we document known FAILs; alert if new regressions appear
    expect(failLines.length).toBeLessThanOrEqual(MAX_ALLOWED_FAILS);
  });
});

// ─── Test 3: italic_audit.md has > 50 total italic spans ─────────────────────

describe('Stage 11 — italic_audit.md has significant italic spans', () => {
  let content;

  beforeAll(() => {
    content = fs.readFileSync(path.join(REPORTS_DIR, 'italic_audit.md'), 'utf8');
  });

  test('file is non-empty', () => {
    expect(content.length).toBeGreaterThan(0);
  });

  test('contains "Total italic spans" header with a number > 50', () => {
    expect(content).toMatch(/Total italic spans across all sections:/);
    const match = content.match(/Total italic spans across all sections:\s*(\d+)/);
    expect(match).not.toBeNull();
    const totalSpans = parseInt(match[1], 10);
    expect(totalSpans).toBeGreaterThan(50);
  });
});

// ─── Test 4: translit_gaps.md exists and is non-empty ────────────────────────

describe('Stage 11 — translit_gaps.md exists and is non-empty', () => {
  test('file exists and is non-empty', () => {
    const p = path.join(REPORTS_DIR, 'translit_gaps.md');
    expect(fs.existsSync(p)).toBe(true);
    const content = fs.readFileSync(p, 'utf8');
    expect(content.length).toBeGreaterThan(0);
    expect(content).toContain('Total:');
  });
});

// ─── Test 5: unanchored_essays.md exists and is non-empty ────────────────────

describe('Stage 11 — unanchored_essays.md exists and is non-empty', () => {
  test('file exists and is non-empty', () => {
    const p = path.join(REPORTS_DIR, 'unanchored_essays.md');
    expect(fs.existsSync(p)).toBe(true);
    const content = fs.readFileSync(p, 'utf8');
    expect(content.length).toBeGreaterThan(0);
    expect(content).toContain('Total:');
  });
});
